---
- name: Deps | import core_dependencies role
  ansible.builtin.import_role:
    name: robertdebock.core_dependencies
  become: true

- name: Deps | import bootstrap role
  ansible.builtin.include_role:
    name: robertdebock.bootstrap
  vars:
    bootstrap_become: true
